### ISSUE TITLE
Short-Term Roadmap

### ISSUE THREAD

**Issue by Z-a-r-a-k-i** [pathwar/pathwar#473]
## Major feat / fixes

1. [ ] Fix challenge url issue on api prod server ("nginx_url": "http://3axaqvfi.local" should be "http://3axaqvfi.pathwar.land")
2. [ ] Split migration into two categories: always VS unit test only, and cleanup always for prod (review @moul)
3. [ ] Add a "default agent" flag on agents that will automatically create challenge instance for each challenges
4. [ ] Add a button that opens challenge url in challenge page
    - [ ] challenge list view -> if 1 instance -> simple button; if > 1 instances -> dropdown menu
    - [ ] single challenge view -> table with instances, last redump, status
7. [ ] Improve UI/UX ->
    - [ ] challenge listing -> super simple view, few info (remove github)
    - [ ] challenge view -> more info -> github, hing, instances, url, description, challenge stats, etc, etc
10. [ ] Fix keycloak confirmation mail issue
11. [ ] Make the challenge validation api call
12. [ ] Activity & Money (@moul)
13. [ ] TESTING
14. [ ] Fix challenge-debug (probably migration file)
15. [ ] Cat docker-compose.yml in tmp folder when debug flag is true

## Minor feat / fixes

1. [ ] Fix page reloading all the time on front (probably related to the 404 error we have for 1s each time we are loading a page)
2. [ ] Why do we have every challenge in double on season page ?
    - be careful -> only take the current season AND if you have multiple flavors, only use the one with the good status -> check the API first, and maybe it needs to be done from the front
3. [ ] Close challenge button not working
4. [ ] Need admin panel to add season / challenge
    - -> CLI
7. [ ] Need admin panel to edit user data
    - -> forestadmin / CLI
8. [ ] Need admin/moderator/dev panel read-only -> OK
